### ISSUE TITLE
登录不了

### ISSUE THREAD

**Issue by xuke6677** [duanluan/ruoyi#1]
Hi ，大神，登陆不了
(https://user-images.githubusercontent.com/12760206/81031143-dfa02900-8ebd-11ea-881f-83eadb6726e6.png)

**Comment by duanluan** [comment]
> Hi ，大神，登陆不了
> (https://user-images.githubusercontent.com/12760206/81031143-dfa02900-8ebd-11ea-881f-83eadb6726e6.png)

若依确实有 Chrome 浏览器（我用的 Cent Browser (Chromium 80.0.3987.163)）无法登录的问题，提示验证码错误，然后我用 Edge 是可以的。但是没有遇到你这种 JS 报错的问题，你是如何启动项目的？

**Comment by xuke6677** [comment]
![image](https://user-images.githubusercontent.com/12760206/81093324-858e7a80-8f34-11ea-867e-345607897af7.png)
![image](https://user-images.githubusercontent.com/12760206/81093425-ad7dde00-8f34-11ea-8c5e-2af214c292b2.png)

直接RUN启动的

**Comment by duanluan** [comment]
重新下载这个库的代码启动试一下，不行的话我可以远程帮你看一下 duanluan 邮箱：duanluan@outlook.com 签名由 网易邮箱大师 定制 在2020年05月06日 00:58，xuke6677 写道： 直接RUN启动的 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by duanluan** [comment]
> ![image](https://user-images.githubusercontent.com/12760206/81093324-858e7a80-8f34-11ea-867e-345607897af7.png)
> ![image](https://user-images.githubusercontent.com/12760206/81093425-ad7dde00-8f34-11ea-8c5e-2af214c292b2.png)
> 
> 直接RUN启动的

重新下载这个库的代码启动试一下，不行的话我可以远程帮你看一下

**Comment by xuke6677** [comment]
今天太晚了，你早点休息吧。改天再帮我远程看一下，谢谢啦

**Comment by duanluan** [comment]
> 今天太晚了，你早点休息吧。改天再帮我远程看一下，谢谢啦

https://get.teamviewer.com/v15/s79174153
